import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/Providers/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <head>
        <link rel="shortcut icon" href="/assets/logo.svg" type="image/x-icon" />
      </head>
      <body
        className={`${inter.variable} antialiased`}
      >
        <NextAuthProvider>
          <NavBar></NavBar>
          <Toaster></Toaster>
          {children}
          <Footer></Footer>
        </NextAuthProvider>

      </body>
    </html>
  );
}
